### ISSUE TITLE
ipc.disconnect does not stop retrying

### ISSUE THREAD

**Issue by RIAEvangelist** [RIAEvangelist/node-ipc#35]
ipc.disconnect('world') will still try to connect event though explicitly disconnecting.

**Comment by RIAEvangelist** [comment]
fixed in [node-ipc v2.0.0](https://github.com/RIAEvangelist/node-ipc/releases/tag/2.0.0)

**Comment by dwelle** [comment]
Still an issue because the [retry timeout](https://github.com/RIAEvangelist/node-ipc/blob/master/dao/client.js#L193) isn't cleared, thus it can fire when the `disconnect()` is called in the middle.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
